name: covid-uk
channels:
  - r
  - defaults
dependencies:
  - nlopt
  - r
  - r-qs
  - r-here
  - r-data.table
  - r-lubridate
  - r-nloptr
  - r-hdinterval
  - r-rcppgsl
  - r-ggplot2
  - r-stringr
  - r-essentials
